# Use base image
FROM base-openldap-img

# Update and install necessary packages
# RUN apt-get update && \
#     apt-get install -y \
#     slapd \
#     ldap-utils \
#     # For network testing commands
#     iputils-ping \
#     netcat-openbsd \
#     dnsutils