# Use base image
FROM base-openldap-sync

# Setup server Id for a N-Way Multi-Provider LDAP synchronisation
# COPY shared_scripts/set_serverId.ldif.sh /tmp/set_serverId.ldif.sh 
# RUN /tmp/set_serverId.ldif.sh 1
# RUN slapadd /tmp/set_serverId.ldif