services:
  # OpenLDAP Service
  openldap:
    hostname: openldap-service
    build:
      context: ./OpenLDAP-Service
    env_file:
      - .env
    container_name: openldap-service
    ports:
      - "389:389"  # LDAP default port
      - "636:636"  # LDAP over TLS
    volumes:
      - shared:/tmp/shared
      - container_ids:/container_ids
    networks:
      - lan_net 

  # Kerberos with OpenLDAP Backend
  kerberos:
    hostname: kerberos-server
    build: 
      context: ./OpenLDAP-Kerberos-Server
    env_file:
      - .env
    container_name: kerberos-server
    ports:
      - "88:88"    # Exposing the Kerberos authentication service (TCP/UDP)
      - "749:749"  # Exposing the Kerberos administration service (TCP)
      # - '389:389'
      # - '636:636'
    volumes:
      - shared:/tmp/shared
      - shared2:/tmp/shared2
      - container_ids:/container_ids
    networks:
      - lan_net

  sssd-client:
    hostname: sssd-client
    build:
      context: ./SSSD-client
    env_file:
      - .env
    container_name: sssd-client
    volumes:
      - shared2:/tmp/shared2
      - container_ids:/container_ids
    networks:
      - lan_net

networks:
  lan_net:
    driver: bridge  # LAN network simulating devices on the same network (Kerberos + OpenLDAP)
  external_net:
    driver: bridge  # Isolated network for external device (SSSD client)

volumes:
  shared:
  shared2:
  container_ids: