services:
  # OpenLDAP Service
  openldap:
    hostname: ${LDAP_SERVICE_HOST}
    domainname: ${ON_PREMISES_NETWORK}
    container_name: ${LDAP_SERVICE_HOST}
    build:
      context: ./OpenLDAP-Service
    env_file: .env
    volumes:
      - shared_ldap:/tmp/shared_kerberos
    networks:
      - ${ON_PREMISES_NETWORK}
    ports:
      - "389:389"  # LDAP default port
      - "636:636"  # LDAP over TLS

  # Kerberos with OpenLDAP Backend
  kerberos:
    hostname: ${KERBEROS_HOST}
    # domainname: ${ON_PREMISES_NETWORK}
    container_name: ${KERBEROS_HOST}
    build: 
      context: ./OpenLDAP-Kerberos-Server
    env_file: .env
    volumes:
      - shared_ldap:/tmp/shared_ldap
      - shared_sssd:/tmp/shared_sssd
    networks:
      - ${ON_PREMISES_NETWORK}
    ports:
      - "88:88"    # Kerberos authentication service (TCP/UDP)
      - "749:749"  # Kerberos administration service (TCP)

  # SSSD Client for Kerberos
  sssd-client:
    hostname: ${SSSD_CLIENT_HOST}
    # domainname: ${ON_PREMISES_NETWORK}
    container_name: ${SSSD_CLIENT_HOST}
    build:
      context: ./SSSD-client
    env_file: .env
    volumes:
      - shared_sssd:/tmp/shared_kerberos
    networks:
      - ${ON_PREMISES_NETWORK}

networks:
  zeepaardje-net:
    driver: bridge  # LAN network simulating devices on the same network (Kerberos + OpenLDAP)
    name: ${ON_PREMISES_NETWORK}
  external_net:
    driver: bridge  # Isolated network for external device

volumes:
  shared_ldap:  # Sharing the keytab from kerberos server to openldap service
  shared_sssd:  # Sharing the keytab from kerberos server to sssd client