services:
  # Kerberos with OpenLDAP Backend as On-Premises IdP
  lan-idp:
    hostname: ${KERBEROS_HOST}
    domainname: ${ON_PREMISES_NETWORK}
    container_name: ${KERBEROS_HOST}.${ON_PREMISES_NETWORK}
    build: 
      context: /Local-IdP
    env_file: .env
    volumes:
      - shared_ldap:/tmp/shared_ldap
      - shared_sssd:/tmp/shared_sssd
    networks:
      - ${ON_PREMISES_NETWORK}
    ports:
      - "88:88"    # Kerberos authentication service (TCP/UDP)
      - "749:749"  # Kerberos administration service (TCP)

  # SSSD Client for Kerberos
  sssd-client:
    hostname: ${SSSD_CLIENT_HOST}
    domainname: ${ON_PREMISES_NETWORK}
    container_name: ${SSSD_CLIENT_HOST}.${ON_PREMISES_NETWORK}
    build:
      context: /SSSD-client
    env_file: .env
    volumes:
      - shared_sssd:/tmp/shared_kerberos
    networks:
      - ${ON_PREMISES_NETWORK}

  # OpenLDAP Service, for testing on-premises Kerberos Authentication
  openldap:
    hostname: ${LDAP_SERVICE_HOST}
    domainname: ${ON_PREMISES_NETWORK}
    container_name: ${LDAP_SERVICE_HOST}.${ON_PREMISES_NETWORK}
    build:
      context: /OpenLDAP-Service
    env_file: .env
    volumes:
      - shared_ldap:/tmp/shared_kerberos
    networks:
      - ${ON_PREMISES_NETWORK}
    ports:
      - "389:389"  # LDAP default port
      - "636:636"  # LDAP over TLS

  # OpenLDAP for Cloud IdP
  cloud-idp:
    hostname: ${CLOUD_IDP_HOST}
    domainname: ${CLOUD_IDP_NETWORK}
    container_name: ${CLOUD_IDP_HOST}.${CLOUD_IDP_NETWORK}
    build:
      context: /Cloud-IdP
    env_file: .env
    networks:
      - ${CLOUD_IDP_NETWORK}

networks:
  zeepaardje-net: # LAN network for on-premises IdP and Services
    driver: bridge
    name: ${ON_PREMISES_NETWORK}
  zeepaardje-cloud-net: # Network for the cloud IdP
    driver: bridge
    name: ${CLOUD_IDP_NETWORK}
  cloud-service1: # Network for a cloud Service
    driver: bridge
    name: ${CLOUD_NETWORK1}

volumes:
  shared_ldap:  # Sharing the keytab from kerberos server to openldap service
  shared_sssd:  # Sharing the keytab from kerberos server to sssd client